export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART",
    REMOVE_PRODUCT_FROM_CART : "REMOVE_PRODUCT_FROM_CART",
    INCREMENT_AMOUNT_PRODUCT_CART : 'INCREMENT_AMOUNT_PRODUCT_CART',
    DECREMENT_AMOUNT_PRODUCT_CART : 'DECREMENT_AMOUNT_PRODUCT_CART'
    
}